export const sensibleData = {
  REPRESENTATIVE: process.env.NEXT_PUBLIC_REPRESENTATIVE,
  IDENTITY_DOCUMENT: process.env.NEXT_PUBLIC_IDENTITY_DOCUMENT,
  ASSOCIATION: process.env.NEXT_PUBLIC_ASSOCIATION,
  CIF: process.env.NEXT_PUBLIC_CIF,
  EMAIL: process.env.NEXT_PUBLIC_EMAIL,
  ADDRESS: process.env.NEXT_PUBLIC_ADDRESS,
  PHONE_NUMBER: process.env.NEXT_PUBLIC_PHONE_NUMBER,
}
